enabled_collectors:
  - github
  - arxiv

enabled_processors:
  - pdf
  - text

directories:
  corpus_root: ./test_data/corpus
  raw_data_dir: ./test_data/raw
  processed_dir: ./test_data/processed
  metadata_dir: ./test_data/metadata
  logs_dir: ./test_data/logs
