# Production master configuration for CryptoFinanceCorpusBuilder
# This file controls the production pipeline from collection to processing

# Environment selection
environment: "production"

# Base configurations for production environment
environments:
  production:
    corpus_dir: "G:/ai_trading_dev/data/production"
    cache_dir: "E:/ai_trading_dev/cache/production"
    log_dir: "G:/ai_trading_dev/logs/production"

# Directory structure configuration
directories:
  raw_data:
    base: "raw_data"
    structure:
      - "{domain}"  # e.g., crypto_derivatives, high_frequency_trading
      - "{content_type}"  # e.g., papers, code, reports
  extracted:
    base: "extracted"
    structure:
      - "{domain}"
      - "{content_type}"
      - "{quality}"  # e.g., high_quality, low_quality
  processed:
    base: "processed"
    structure:
      - "{domain}"
      - "{content_type}"
      - "{processor}"  # e.g., quality_checked, balanced
  reports:
    base: "reports"
    structure:
      - "{domain}"
      - "{report_type}"  # e.g., quality, balance, statistics
  logs:
    base: "logs"
    structure:
      - "{component}"  # e.g., collectors, extractors, processors
  cache:
    base: "cache"
    structure:
      - "{domain}"
      - "{content_type}"
  temp:
    base: "temp"
    structure:
      - "{domain}"
      - "{process}"  # e.g., extraction, processing

# Collector configurations
collectors:
  arxiv:
    enabled: true
    categories: 
      - "q-fin"
      - "cs.AI"
      - "cs.LG"
    max_results: 100
    delay_range: [3, 7]
    output_dir: "{corpus_dir}/raw_data/{domain}/papers"
    domains:
      - "crypto_derivatives"
      - "high_frequency_trading"
      - "portfolio_construction"
      - "risk_management"
    quality_checks:
      min_papers: 50
      max_retries: 3
      timeout: 30

  scidb:
    enabled: true
    max_results_per_term: 10
    delay_range: [3, 7]
    output_dir: "{corpus_dir}/raw_data/{domain}/papers"
    domains:
      - "crypto_derivatives"
      - "high_frequency_trading"
      - "portfolio_construction"
      - "risk_management"
      - "market_microstructure"
      - "trading_strategies"
    quality_checks:
      min_papers: 30
      max_retries: 3
      timeout: 30

  github:
    enabled: true
    topics:
      - "cryptocurrency"
      - "trading"
      - "defi"
      - "blockchain"
    min_stars: 100
    max_results: 50
    output_dir: "{corpus_dir}/raw_data/{domain}/code"
    quality_checks:
      min_repos: 20
      max_retries: 3
      timeout: 30

# Extractor configurations
extractors:
  pdf:
    enabled: true
    min_tokens: 200
    quality_threshold: 0.8
    chunk_size: 1000
    overlap: 200
    input_dir: "{corpus_dir}/raw_data"
    output_dir: "{corpus_dir}/extracted/pdf"
    domains:
      - "crypto_derivatives"
      - "high_frequency_trading"
      - "portfolio_construction"
      - "risk_management"
    processing:
      max_workers: 4
      batch_size: 10
      timeout: 300

  nonpdf:
    enabled: true
    min_tokens: 100
    quality_threshold: 0.7
    chunk_size: 800
    overlap: 150
    input_dir: "{corpus_dir}/raw_data"
    output_dir: "{corpus_dir}/extracted/nonpdf"
    domains:
      - "crypto_derivatives"
      - "high_frequency_trading"
      - "portfolio_construction"
      - "risk_management"
    processing:
      max_workers: 4
      batch_size: 10
      timeout: 300

# Processor configurations
processors:
  quality_control:
    enabled: true
    input_dir: "{corpus_dir}/extracted"
    output_dir: "{corpus_dir}/processed/quality_checked"
    checks:
      language:
        enabled: true
        min_confidence: 0.8
        supported_languages: ["en"]
      corruption:
        enabled: true
        min_quality: 0.7
      duplication:
        enabled: true
        similarity_threshold: 0.8
      translation:
        enabled: true
        min_confidence: 0.9
    processing:
      max_workers: 4
      batch_size: 20
      timeout: 600

  corpus_balancer:
    enabled: true
    input_dir: "{corpus_dir}/processed/quality_checked"
    output_dir: "{corpus_dir}/processed/balanced"
    target_ratios:
      crypto_derivatives: 0.2
      high_frequency_trading: 0.2
      portfolio_construction: 0.15
      risk_management: 0.15
      market_microstructure: 0.1
      trading_strategies: 0.1
    processing:
      max_workers: 2
      batch_size: 50
      timeout: 1200

  specialized:
    charts:
      enabled: true
      input_dir: "{corpus_dir}/processed/balanced"
      output_dir: "{corpus_dir}/processed/specialized/charts"
      min_confidence: 0.7
      processing:
        max_workers: 2
        batch_size: 10
        timeout: 300

    formulas:
      enabled: true
      input_dir: "{corpus_dir}/processed/balanced"
      output_dir: "{corpus_dir}/processed/specialized/formulas"
      min_confidence: 0.8
      processing:
        max_workers: 2
        batch_size: 10
        timeout: 300

    symbols:
      enabled: true
      input_dir: "{corpus_dir}/processed/balanced"
      output_dir: "{corpus_dir}/processed/specialized/symbols"
      min_confidence: 0.75
      processing:
        max_workers: 2
        batch_size: 10
        timeout: 300

# Logging configuration
logging:
  level: "INFO"
  file: "{log_dir}/corpus_builder.log"
  max_size: 10485760  # 10MB
  backup_count: 5
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  collectors:
    file: "{log_dir}/collectors.log"
    level: "INFO"
  extractors:
    file: "{log_dir}/extractors.log"
    level: "INFO"
  processors:
    file: "{log_dir}/processors.log"
    level: "INFO" 