name: Test

on:
  push:
  pull_request:

jobs:
  pytest:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: |
            CorpusBuilderApp/requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r CorpusBuilderApp/requirements.txt
          pip install ruff pytest pytest-cov
      - name: Lint
        run: ruff check .
      - name: Run tests
        env:
          PYTEST_QT_STUBS: '0'
          PYTEST_QT_API: 'pyside6'
        run: |
          pytest -m "not skip" --cov=. --cov-report=xml --cov-report=term --cov-fail-under=95
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml
